wokwi/wokwi-builders

- esp32-rust/Dockerfile
- esp32-rust/compile.sh
Yesterday we [updated the esp-idf folder name](https://github.com/SergioGasquez/esp-rs-container/commit/9bd3cd470e413c018643deca67b9485c3a7c714c) to be more generic.
The images are still hosted under my personal Dockerhub account and they are changing rapidly (sorry for that), we plan on moving them under the espressif's Dockerhub account in the upcoming weeks where they will be way more stable.
> Update esp-idf folder name

- esp32-rust/Cargo.toml
- esp32-rust/compile.sh
- esp32-rust/fetch.sh
- esp32c3-rust/Cargo.toml
- esp32c3-rust/Dockerfile
- esp32c3-rust/compile.sh
- esp32c3-rust/fetch.sh
- esp32c3-training/Cargo.toml
- esp32c3-training/Dockerfile
- esp32c3-training/compile.sh
- esp32c3-training/fetch.sh
- esp32s2-rust/Cargo.toml
- esp32s2-rust/Dockerfile
- esp32s2-rust/compile.sh
- esp32s2-rust/fetch.sh
- Since we no longer have images for all boards, I have split the builders per target. 
- Added a fetch script that fetches dependencies and build the project
- Compile scripts now uses `--offline` argument
- Use [esp-rs/esp-idf-template](https://github.com/esp-rs/esp-idf-template) as base project with a custom `Cargo.toml` which includes common dependencies.
- Added esp32c3-training builder for Ferrous System training.
> Update build containers

- rust-nostd-esp32/Cargo.toml
- rust-nostd-esp32c3/Cargo.toml
- rust-nostd-esp32s2/Cargo.toml
Added new dependencies to cover as more as possible user needs, added `eh1` feature(not builds without it), added `xtensa-atomic-emulation-trap` dependency for `esp32` and `esp32s2` chips
> Updated Cargo.toml

- rust-nostd-esp/Dockerfile
When using `alloc` option of the template, the `.cargo/config.toml` will include [the necessary options to allocate](https://github.com/esp-rs/esp-template/blob/6c00b41b25732208f82f9bc0cbbec84f24b249bd/.cargo/config.toml#L45).
At the moment you can include the [`esp-alloc` crate](https://crates.io/crates/esp-alloc) on the `Cargo.toml`, but as users cannot edit the `.cargo/config.toml` they will not be able to use it.
> Enable alloc

- rust-nostd-esp/Dockerfile
- rust-nostd-esp/compile.sh
- rust-std-esp32/Cargo.toml
- rust-std-esp32/Dockerfile
- rust-std-esp32c3/Cargo.toml
- rust-std-esp32c3/Dockerfile
- rust-std-esp32s2/Cargo.toml
- rust-std-esp32s2/Dockerfile
- Update builders to use `latest` tag instead of hardcoded version
- Add cargo audit check to `rust-nostd-esp` builder
- Update dependencies for std builders
> Update builders and add audit

- rust-std-esp32c3/Cargo.toml
- Updated `riscv-rt `crate as v0.10 was yanked 
- Other minor updates
CI test: https://github.com/SergioGasquez/wokwi-builders/actions/runs/4302220698
`rust-training-esp32c3` is also failing, but I would suggest addressing this builder once we have the training in a better spot (we are currently working on this as the repo just got transferred to our organization)
> Fix rust-std-esp32c3 builder

- zephyr-esp32/Dockerfile
The previous container was building the entire container from scratch. Instead, the new builder is using a pre-built, optimized container from https://github.com/beriberikix/zephyr-docker.
> Make Zephyr build container much faster

- rust-nostd-esp/Dockerfile
- rust-nostd-esp/compile.sh
Before, if a user modified the "name" property of Cargo.toml, the build would fail. Now, the name provided by the user will be replaced by the correct one and the build wont fail.
Also updated the Xtensa Rust version
> Allow changing the name of the project in Cargo.toml

- rust-training-esp32c3/Cargo.toml
- rust-training-esp32c3/Dockerfile
- rust-training-esp32c3/cfg.toml
- rust-training-esp32c3/compile.sh
- rust-training-esp32c3/fetch.sh
- rust-training-esp32c3/sdkconfig.defaults
Our training had a big revamp: https://github.com/esp-rs/espressif-trainings/pull/152 and now the Dockerfile from the training [gets published in dockerhub](https://hub.docker.com/r/espressif/rust-std-training). 
I will try to create a project for the exercise and solution for all the projects of the training and link them in the training content.
> Update rust-training-esp32c3 image

- zephyr-esp32/Dockerfile
- zephyr-esp32/west.yml
This builds on https://github.com/wokwi/wokwi-builders/pull/27 by only downloading the minimum need for an Espressif app, namely the Espressif HAL. It still pulls in the main Zephyr repo but any future applications that say need MCUBoot or OpenThread, but those can be added as needed instead of pulling the entire tree.
The directory file structure had to change so please verify in Wokwi before merging!
Thanks for @hasheddan for helping on this.
> Improve build time by limiting to Espressif HAL

- rust-nostd-esp/Dockerfile
When slimming down the base image, we also removed `sccache`
> Add sccache

- rust-std-esp32/Dockerfile
- rust-std-esp32c3/Dockerfile
- rust-std-esp32s2/Dockerfile
- rust-std-esp32s3/Dockerfile
We've just updated `esp-idf-template` and we added a prompt for newbies which saves some more detailed prompts. For more details see: https://github.com/esp-rs/esp-idf-template/issues/95 and https://github.com/esp-rs/esp-idf-template/pull/100 for more details.
This also makes maintaining the builders easier, as we do not need to edit the builder for every prompt that we add/edit since every prompt will use its default.
> Update cargo generate prompts for std builders

- rust-nostd-esp/Dockerfile
This allows building `no_std` projects with `esp-alloc` like https://wokwi.com/projects/346697192934736467
> Add alloc to build-std property

- verilog-cxxrtl/project/main.cpp
Added treating CXXRTL_OUTLINE objects as outputs and it also required calling outline->eval() to update their values to be read from curr[]
Tested it locally with
Yosys 0.21+18 (git sha1 fcd1be142, clang 10.0.0-4ubuntu1 -fPIC -Os)
Wokwi circuit to validate:
https://wokwi.com/projects/366564630633368577
> FIX: Complex Verilog modules always output zeros

- rust-std-esp/compile.sh
In order to fix #47 I created https://github.com/esp-rs/rust-build/pull/227 where I added `openssl` as a dependency.
> Run cargo-audit for std

- rust-nostd-avr/Dockerfile
- rust-nostd-esp/Dockerfile
After doing some testing, I was not able to install cargo-audit with artifacts of the GH releases as it generates a lot of issues with openSSL. This seems to work: https://github.com/SergioGasquez/wokwi-builders/actions/runs/5666221085
> Install cargo-audit with Cargo

- rust-nostd-esp/Dockerfile
- rust-nostd-esp/compile.sh
- rust-std-esp/Dockerfile
- rust-std-esp/compile.sh
- rust-training-esp32c3/compile.sh
Updates Xtensa Rust version to 1.72
Since https://github.com/esp-rs/rust-build/pull/233 we no longer have python3 installed in the docker image, but `espflash` is installed, so I switched to use it instead of installing `esptool`.
Successful CI run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/6377579127
> Update Xtensa Rust and use espflash

- rust-nostd-esp/Dockerfile
- rust-std-esp/Dockerfile
Since `std` builder MSRV is now 1.75.
Successful CI run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/7697310220
> Update base images for esp-rs builders

- .github/workflows/build-rust.yml
- rust-nostd-esp/Dockerfile
- rust-std-esp/Dockerfile
Just noticed that no_std builder was also failing due to the base image. 
- Update base images
- Avoid building H2 for std check so we get it green. I'll revert this when we have a new release. Let me know if you prefer to have it failing until the next release and I'll revert this change.
- Update `action/checkout` to avoid NodeJS warning
CI Run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/8556420537
> Update base images

- rust-nostd-esp/Dockerfile
- rust-nostd-esp/config.toml
- rust-std-esp/Dockerfile
- Update base images to 1.78
- Unpin `cargo-audit` version
- Add `-a` flag to `cargo-generate` command
Successful CI run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/9030300476
> Fix esp builders

- rust-nostd-esp/compile.sh
We switched the template to use [`stable` channel](https://github.com/esp-rs/esp-template/pull/167) and in CI we were using some unstable flags that required `nightly`.
Sorry for taking this long to fix it, it slipped under my radar.
Successful CI run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/10919171387
> Fix no_std esp builds

- rust-nostd-esp/Dockerfile
- rust-nostd-esp/compile.sh
- rust-std-esp/Dockerfile
- rust-training-esp32c3/Cargo.toml
- Replace esp-template for esp-generate
- Use latest base image
CI Run: https://github.com/SergioGasquez/wokwi-builders/actions/runs/11892658431/job/33135976000
> Use esp-generate in no_std builder
